import { Link } from 'react-router-dom';

const STACK = [
  { layer: 'Frontend', tech: 'React + Vite + Tailwind CSS', role: 'Beekeeper, admin, and consumer interfaces.' },
  { layer: 'Backend API', tech: 'Node.js + Express', role: 'Authentication, hive/batch management, traceability, blockchain glue.' },
  { layer: 'Database', tech: 'PostgreSQL', role: 'All application data — users, hives, sensor readings, batches, alerts.' },
  { layer: 'AI Service', tech: 'Python + FastAPI + scikit-learn', role: 'Disease-risk classification and honey yield prediction (RandomForest models).' },
  { layer: 'Blockchain', tech: 'Solidity + Hardhat + ethers.js', role: 'Tamper-evident integrity layer for batch traceability events.' },
  { layer: 'IoT Layer', tech: 'Simulated sensor generator', role: 'Stands in for real hive sensors; same API shape so real hardware can plug in later.' },
];

const DISCLAIMERS = [
  {
    title: 'AI predictions are estimates, not diagnoses',
    body: 'The disease-risk and yield models are trained on synthetic environmental/behavioral data for this prototype. They are not a substitute for laboratory testing or veterinary inspection.',
  },
  {
    title: 'Blockchain verifies integrity, not purity',
    body: 'The blockchain proves that recorded traceability events have not been tampered with after the fact. It does not and cannot verify chemical purity or the absence of adulteration — that requires laboratory testing.',
  },
  {
    title: 'IoT sensors are simulated for this prototype',
    body: 'Sensor readings are generated by a realistic simulator, not physical hardware. The API is designed so real sensors can be connected later without changing the rest of the system.',
  },
  {
    title: 'Notifications are simulated',
    body: 'Email/WhatsApp alert notifications shown in the app are logged and displayed for demonstration, but no real messages are sent to any real address or phone number.',
  },
];

export default function About() {
  return (
    <div className="min-h-screen bg-honey-50 dark:bg-gray-900">
      <header className="max-w-4xl mx-auto px-6 py-6 flex items-center justify-between">
        <Link to="/" className="font-bold text-xl text-honey-900 dark:text-honey-100">🐝 HoneyChain</Link>
        <Link to="/" className="text-sm text-honey-600">← Back home</Link>
      </header>

      <main className="max-w-4xl mx-auto px-6 pb-16">
        <h1 className="text-3xl font-bold text-honey-900 dark:text-honey-100 mb-2">How HoneyChain Works</h1>
        <p className="text-gray-500 dark:text-gray-400 mb-10">
          Built for Smart India Hackathon 2026 — SIH26021. A digital trust and intelligence
          platform for rural beekeeping: traceability, AI-assisted hive insights, and
          transparent supply chains, in one integrated product.
        </p>

        <h2 className="text-xl font-semibold text-honey-900 dark:text-honey-100 mb-4">Technology Stack</h2>
        <div className="bg-white dark:bg-gray-800 rounded-xl border border-honey-100 dark:border-gray-700 overflow-hidden mb-10">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-gray-400 dark:text-gray-500 border-b border-honey-100 dark:border-gray-700 bg-honey-50">
                <th className="py-3 px-4">Layer</th>
                <th className="py-3 px-4">Technology</th>
                <th className="py-3 px-4">Role</th>
              </tr>
            </thead>
            <tbody>
              {STACK.map((s) => (
                <tr key={s.layer} className="border-b border-honey-50 last:border-0">
                  <td className="py-3 px-4 font-semibold text-honey-900 dark:text-honey-100">{s.layer}</td>
                  <td className="py-3 px-4 text-gray-600 dark:text-gray-300">{s.tech}</td>
                  <td className="py-3 px-4 text-gray-500 dark:text-gray-400">{s.role}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <h2 className="text-xl font-semibold text-honey-900 dark:text-honey-100 mb-4">Important Limitations</h2>
        <div className="space-y-4">
          {DISCLAIMERS.map((d) => (
            <div key={d.title} className="bg-white dark:bg-gray-800 rounded-xl border border-honey-100 dark:border-gray-700 p-5">
              <h3 className="font-semibold text-honey-900 dark:text-honey-100 mb-1">{d.title}</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">{d.body}</p>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}
